export const types = {
  NEW_TASK: 'NEW_TASK',
  TASKS_REQUEST: 'TASKS_REQUEST',
  TASKS_SUCCESS: 'TASKS_SUCCESS',
  TASKS_FAILURE: 'TASKS_FAILURE',
  SET_STATUS: 'SET_STATUS',
  DELETE_TASK: 'DELETE_TASK',
  COUNT_TASKS_ACTIVAS: 'COUNT_TASKS_ACTIVAS',
};
